### ISSUE TITLE
Download, transform, clean, and publish the census data at ODN

### ISSUE THREAD

**Issue by nikeshbalami** [okfnepal/nationalcensus-2021#1]
**TODO**
- [x] Download the datasets: 
- [x] https://censusnepal.cbs.gov.np/Home/Details?tpid=5&dcid=a82d0762-6f49-4752-a02d-19fdaddc55ed&tfsid=17
- [x] Transform the datasets into English
- [x] Clean and validate
- [x] Publish it at ODN

**Comment by nikeshbalami** [comment]
Datasets have been published.
